"""modify caracteristics entity

Revision ID: 1891eeeaa700
Revises: fc681e60e977
Create Date: 2025-04-18 13:17:12.332495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1891eeeaa700'
down_revision: Union[str, None] = 'fc681e60e977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caracteristics', sa.Column('nationality', sa.String(), nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('last_name', sa.String(), nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('first_name', sa.String(), nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('play_hand', sa.String(), nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('back_hand', sa.Integer(), nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('height_cm', sa.Integer(), nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('weight_kg', sa.Integer(), nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('pro_year', sa.Integer(), nullable=True), schema='data')
    op.drop_column('caracteristics', 'date_turned_pro', schema='data')
    op.drop_column('caracteristics', 'height', schema='data')
    op.drop_column('caracteristics', 'weight', schema='data')
    op.drop_column('caracteristics', 'handedness', schema='data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caracteristics', sa.Column('handedness', sa.VARCHAR(), autoincrement=False, nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='data')
    op.add_column('caracteristics', sa.Column('date_turned_pro', sa.VARCHAR(), autoincrement=False, nullable=True), schema='data')
    op.drop_column('caracteristics', 'pro_year', schema='data')
    op.drop_column('caracteristics', 'weight_kg', schema='data')
    op.drop_column('caracteristics', 'height_cm', schema='data')
    op.drop_column('caracteristics', 'back_hand', schema='data')
    op.drop_column('caracteristics', 'play_hand', schema='data')
    op.drop_column('caracteristics', 'first_name', schema='data')
    op.drop_column('caracteristics', 'last_name', schema='data')
    op.drop_column('caracteristics', 'nationality', schema='data')
    # ### end Alembic commands ###
