"""add first tables

Revision ID: 315d7604a82e
Revises: 408247088ca9
Create Date: 2025-04-17 11:27:24.479425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315d7604a82e'
down_revision: Union[str, None] = '408247088ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tennis_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_table('caracteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('handedness', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('date_turned_pro', sa.String(), nullable=True),
    sa.Column('fk_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_player_id'], ['data.player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('winner_rank', sa.Integer(), nullable=True),
    sa.Column('winner_points', sa.Integer(), nullable=True),
    sa.Column('loser_rank', sa.Integer(), nullable=True),
    sa.Column('loser_points', sa.Integer(), nullable=True),
    sa.Column('tournament_name', sa.String(), nullable=True),
    sa.Column('tournament_series', sa.String(), nullable=True),
    sa.Column('tournament_surface', sa.String(), nullable=True),
    sa.Column('tournament_court', sa.String(), nullable=True),
    sa.Column('tournament_round', sa.String(), nullable=True),
    sa.Column('tournament_location', sa.String(), nullable=True),
    sa.Column('fk_winner_id', sa.Integer(), nullable=False),
    sa.Column('fk_loser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_loser_id'], ['data.player.id'], ),
    sa.ForeignKeyConstraint(['fk_winner_id'], ['data.player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('winner', sa.Float(), nullable=True),
    sa.Column('loser', sa.Float(), nullable=True),
    sa.Column('fk_match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_match_id'], ['data.match.id'], ),
    sa.ForeignKeyConstraint(['fk_match_id'], ['data.match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_match_id', 'bookmaker', name='uq_odds_match_bookmaker'),
    schema='data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds', schema='data')
    op.drop_table('match', schema='data')
    op.drop_table('caracteristics', schema='data')
    op.drop_table('player', schema='data')
    # ### end Alembic commands ###
