"""add entities

Revision ID: fc681e60e977
Revises: 315d7604a82e
Create Date: 2025-04-17 23:17:58.236176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc681e60e977'
down_revision: Union[str, None] = '315d7604a82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('caracteristics_fk_player_id_fkey', 'caracteristics', schema='data', type_='foreignkey')
    op.create_foreign_key('caracteristics_fk_player_id_fkey', 'caracteristics', 'player', ['fk_player_id'], ['id'], source_schema='data', referent_schema='data', ondelete='CASCADE')
    op.create_unique_constraint('uq_date_fk_winner_id_fk_loser_id', 'match', ['date', 'fk_winner_id', 'fk_loser_id'], schema='data')
    op.drop_constraint('match_fk_winner_id_fkey', 'match', schema='data', type_='foreignkey')
    op.drop_constraint('match_fk_loser_id_fkey', 'match', schema='data', type_='foreignkey')
    op.create_foreign_key('match_fk_winner_id_fkey', 'match', 'player', ['fk_winner_id'], ['id'], source_schema='data', referent_schema='data', ondelete='CASCADE')
    op.create_foreign_key('match_fk_loser_id_fkey', 'match', 'player', ['fk_loser_id'], ['id'], source_schema='data', referent_schema='data', ondelete='CASCADE')
    op.create_foreign_key('odds_fk_match_id_fkey', 'odds', 'match', ['fk_match_id'], ['id'], source_schema='data', referent_schema='data', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('odds_fk_match_id_fkey', 'odds', schema='data', type_='foreignkey')
    op.drop_constraint('match_fk_loser_id_fkey', 'match', schema='data', type_='foreignkey')
    op.drop_constraint('match_fk_winner_id_fkey', 'match', schema='data', type_='foreignkey')
    op.create_foreign_key('match_fk_loser_id_fkey', 'match', 'player', ['fk_loser_id'], ['id'], source_schema='data', referent_schema='data')
    op.create_foreign_key('match_fk_winner_id_fkey', 'match', 'player', ['fk_winner_id'], ['id'], source_schema='data', referent_schema='data')
    op.drop_constraint('uq_date_fk_winner_id_fk_loser_id', 'match', schema='data', type_='unique')
    op.drop_constraint('caracteristics_fk_player_id_fkey', 'caracteristics', schema='data', type_='foreignkey')
    op.create_foreign_key('caracteristics_fk_player_id_fkey', 'caracteristics', 'player', ['fk_player_id'], ['id'], source_schema='data', referent_schema='data')
    # ### end Alembic commands ###
